chat: 'on'
maintenance: 'off'
modspace: "0 151 0"
spawnspace: "0 151 0"

Ranker:
  messagesend: "§f: "
  administrateur:
    prefix: "§c"
    messages: "§c[Administration] "
    cmd: "admin"
  responsable:
    prefix: "§6"
    messages: "§6[Responsable] "
    cmd: "resp"
  moderateur:
    prefix: "§b"
    messages: "§b[Moderation] "
    cmd: "mod"
  joueur:
    prefix: "§7"
    messages: "§7[Joueur] "

Logs:
  status: "on"
  joinandquit: "on"
  move: "on"
  placeandbreak: "on"
  moderation: "on"
  chat: "on"
  spawnandrespawn: "on"